import _ from "lodash";

export const Institutions = {
    "institutionId": "000000000000000000",
    "code": "10900",
    "name": "ກົມສ່ວຍສາອາກອນ ",
    "remark": "Tax Department",
    "parentCode": "",
    "level": 1,
    "firstCode": null,
    "firstId": null,
    "firstName": null,
    "secondCode": null,
    "secondId": null,
    "secondName": null,
    "children": [
        {
            "institutionId": "000000000000010000",
            "code": "20100",
            "name": "ນະຄອນຫຼວງວຽງຈັນ",
            "remark": "Vientiane Capital",
            "parentCode": "000000000000000000",
            "level": 2,
            "firstCode": null,
            "firstId": null,
            "firstName": null,
            "secondCode": null,
            "secondId": null,
            "secondName": null,
            "children": [
                {
                    "institutionId": "000000000000010100",
                    "code": "20101",
                    "name": "ເມືອງ ຈັນ​ທະ​ບູ​ລີ",
                    "remark": "Chanthabuly District",
                    "parentCode": "000000000000010000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000010200",
                    "code": "20102",
                    "name": "ເມືອງ ສີ​ໂຄດ​ຕະ​ບອງ",
                    "remark": "Sikhottabong District",
                    "parentCode": "000000000000010000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000010300",
                    "code": "20103",
                    "name": "ເມືອງ ໄຊ​ເຊດ​ຖາ",
                    "remark": "Xaysetha District",
                    "parentCode": "000000000000010000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000010400",
                    "code": "20104",
                    "name": "ເມືອງ ສີ​ສັດ​ຕະ​ນາກ",
                    "remark": "Sisattanak District",
                    "parentCode": "000000000000010000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000010500",
                    "code": "20105",
                    "name": "ເມືອງ ນາ​ຊາຍ​ທອງ",
                    "remark": "Naxaithong District",
                    "parentCode": "000000000000010000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000010600",
                    "code": "20106",
                    "name": "ເມືອງ ໄຊ​ທາ​ນີ",
                    "remark": "Xaythany District",
                    "parentCode": "000000000000010000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000010700",
                    "code": "20107",
                    "name": "ເມືອງ ຫາດ​ຊາຍ​ຟອງ",
                    "remark": "Hadxaifong District",
                    "parentCode": "000000000000010000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000010800",
                    "code": "20108",
                    "name": "ເມືອງ ສັງ​ທອງ",
                    "remark": "Sangthong District",
                    "parentCode": "000000000000010000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000010900",
                    "code": "20109",
                    "name": "ເມືອງ ປາກ​ງື່ມ",
                    "remark": "parkngum District",
                    "parentCode": "000000000000010000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                }
            ]
        },
        {
            "institutionId": "000000000000020000",
            "code": "20200",
            "name": "ແຂວງ ຜົ້ງ​ສາ​ລີ",
            "remark": "Phongsaly",
            "parentCode": "000000000000000000",
            "level": 2,
            "firstCode": null,
            "firstId": null,
            "firstName": null,
            "secondCode": null,
            "secondId": null,
            "secondName": null,
            "children": [
                {
                    "institutionId": "000000000000020100",
                    "code": "20201",
                    "name": "ເມືອງ ຜົ້ງ​ສາ​ລີ",
                    "remark": "Phongsaly District",
                    "parentCode": "000000000000020000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000020200",
                    "code": "20202",
                    "name": "ເມືອງ ​ໃໝ່",
                    "remark": "May District",
                    "parentCode": "000000000000020000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000020300",
                    "code": "20203",
                    "name": "ເມືອງ ຂວາ",
                    "remark": "Khua District",
                    "parentCode": "000000000000020000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000020400",
                    "code": "20204",
                    "name": "ເມືອງ ສຳ​ພັນ",
                    "remark": "Samphanh District",
                    "parentCode": "000000000000020000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000020500",
                    "code": "20205",
                    "name": "ເມືອງ ​ບຸນ​ເໜືອ",
                    "remark": "Boonneua District",
                    "parentCode": "000000000000020000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000020600",
                    "code": "20206",
                    "name": "ເມືອງ ຍອດ​​ອູ",
                    "remark": "Nhot ou District",
                    "parentCode": "000000000000020000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000020700",
                    "code": "20207",
                    "name": "ເມືອງ ​ບຸນ​ໃຕ້",
                    "remark": "Boontai District",
                    "parentCode": "000000000000020000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                }
            ]
        },
        {
            "institutionId": "000000000000030000",
            "code": "20300",
            "name": "ແຂວງ ຫຼວງ​ນ້ຳ​ທາ",
            "remark": "Luangnamtha",
            "parentCode": "000000000000000000",
            "level": 2,
            "firstCode": null,
            "firstId": null,
            "firstName": null,
            "secondCode": null,
            "secondId": null,
            "secondName": null,
            "children": [
                {
                    "institutionId": "000000000000030100",
                    "code": "20301",
                    "name": "ເມືອງ ຫລວງນ້ຳ​ທາ",
                    "remark": "Luangnamtha District",
                    "parentCode": "000000000000030000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000030200",
                    "code": "20302",
                    "name": "ເມືອງ ສິງ",
                    "remark": "Sing District",
                    "parentCode": "000000000000030000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000030300",
                    "code": "20303",
                    "name": "ເມືອງ ລອງ",
                    "remark": "Long District",
                    "parentCode": "000000000000030000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000030400",
                    "code": "20304",
                    "name": "ເມືອງ ວຽງ​ພູ​ຄາ",
                    "remark": "Viengphoukha District",
                    "parentCode": "000000000000030000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000030500",
                    "code": "20305",
                    "name": "ເມືອງ ນາ​ແລ",
                    "remark": "Nalae District",
                    "parentCode": "000000000000030000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                }
            ]
        },
        {
            "institutionId": "000000000000040000",
            "code": "20400",
            "name": "ແຂວງ ອຸ​ດົມ​ໄຊ",
            "remark": "Oudomxay",
            "parentCode": "000000000000000000",
            "level": 2,
            "firstCode": null,
            "firstId": null,
            "firstName": null,
            "secondCode": null,
            "secondId": null,
            "secondName": null,
            "children": [
                {
                    "institutionId": "000000000000040100",
                    "code": "20401",
                    "name": "ເມືອງ ໄຊ",
                    "remark": "Xay District",
                    "parentCode": "000000000000040000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000040200",
                    "code": "20402",
                    "name": "ເມືອງ ຫຼາ",
                    "remark": "La District",
                    "parentCode": "000000000000040000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000040300",
                    "code": "20403",
                    "name": "ເມືອງ ນາ​ໝໍ້",
                    "remark": "Namor District",
                    "parentCode": "000000000000040000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000040400",
                    "code": "20404",
                    "name": "ເມືອງ ງາ",
                    "remark": "Nga District",
                    "parentCode": "000000000000040000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000040500",
                    "code": "20405",
                    "name": "ເມືອງ ​ແບງ",
                    "remark": "Beng District",
                    "parentCode": "000000000000040000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000040600",
                    "code": "20406",
                    "name": "ເມືອງ ຮຸນ",
                    "remark": "Hoon District",
                    "parentCode": "000000000000040000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000040700",
                    "code": "20407",
                    "name": "ເມືອງ ປາກ​ແບງ",
                    "remark": "Pakbeng District",
                    "parentCode": "000000000000040000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                }
            ]
        },
        {
            "institutionId": "000000000000050000",
            "code": "20500",
            "name": "ແຂວງ ບໍ່​ແກ້ວ",
            "remark": "Bokeo",
            "parentCode": "000000000000000000",
            "level": 2,
            "firstCode": null,
            "firstId": null,
            "firstName": null,
            "secondCode": null,
            "secondId": null,
            "secondName": null,
            "children": [
                {
                    "institutionId": "000000000000050100",
                    "code": "20501",
                    "name": "ເມືອງ ຫ້ວຍ​ຊາຍ",
                    "remark": "Huoixai District",
                    "parentCode": "000000000000050000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000050200",
                    "code": "20502",
                    "name": "ເມືອງ ຕົ້ນ​ເຜີ້ງ",
                    "remark": "Tonpheung District",
                    "parentCode": "000000000000050000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000050300",
                    "code": "20503",
                    "name": "ເມືອງ ເມິງ",
                    "remark": "Meung District",
                    "parentCode": "000000000000050000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000050400",
                    "code": "20504",
                    "name": "ເມືອງ ຜາ​ອຸດົມ",
                    "remark": "Pha oudom District",
                    "parentCode": "000000000000050000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000050500",
                    "code": "20505",
                    "name": "ເມືອງ ປາກ​ທາ",
                    "remark": "Paktha District",
                    "parentCode": "000000000000050000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                }
            ]
        },
        {
            "institutionId": "000000000000060000",
            "code": "20600",
            "name": "ແຂວງ ຫຼວງ​ພະ​ບາງ",
            "remark": "Luangprabang",
            "parentCode": "000000000000000000",
            "level": 2,
            "firstCode": null,
            "firstId": null,
            "firstName": null,
            "secondCode": null,
            "secondId": null,
            "secondName": null,
            "children": [
                {
                    "institutionId": "000000000000060100",
                    "code": "20601",
                    "name": "ນະ​ຄອນ​ຫຼວງ​ພະ​ບາງ",
                    "remark": "Luangprabang District",
                    "parentCode": "000000000000060000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000060200",
                    "code": "20602",
                    "name": "ເມືອງ ຊຽງ​ເງິນ",
                    "remark": "Xieng ngeun District",
                    "parentCode": "000000000000060000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000060300",
                    "code": "20603",
                    "name": "ເມືອງ ນານ",
                    "remark": "Nan District",
                    "parentCode": "000000000000060000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000060400",
                    "code": "20604",
                    "name": "ເມືອງ ປາກ​ອູ",
                    "remark": "Park ou District",
                    "parentCode": "000000000000060000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000060500",
                    "code": "20605",
                    "name": "ເມືອງ ນ້ຳ​ບາກ",
                    "remark": "Nambak District",
                    "parentCode": "000000000000060000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000060600",
                    "code": "20606",
                    "name": "ເມືອງ ງອຍ",
                    "remark": "Ngoi District",
                    "parentCode": "000000000000060000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000060700",
                    "code": "20607",
                    "name": "ເມືອງ ປາກ​ແຊງ",
                    "remark": "Pak xeng District",
                    "parentCode": "000000000000060000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000060800",
                    "code": "20608",
                    "name": "ເມືອງ ໂພນ​ໄຊ",
                    "remark": "Phonxay District",
                    "parentCode": "000000000000060000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000060900",
                    "code": "20609",
                    "name": "ເມືອງ ຈອມ​ເພັດ",
                    "remark": "Chomphet District",
                    "parentCode": "000000000000060000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000061000",
                    "code": "20610",
                    "name": "ເມືອງ ວຽງ​ຄຳ",
                    "remark": "Viengkham District",
                    "parentCode": "000000000000060000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000061100",
                    "code": "20611",
                    "name": "ເມືອງ ພູ​ຄູນ",
                    "remark": "Phoukhoune District",
                    "parentCode": "000000000000060000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000061200",
                    "code": "20612",
                    "name": "ເມືອງ ໂພນ​ທອງ",
                    "remark": "Phonthong District",
                    "parentCode": "000000000000060000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                }
            ]
        },
        {
            "institutionId": "000000000000070000",
            "code": "20700",
            "name": "​ແຂວງ ຫົວ​ພັນ",
            "remark": "Huaphanh",
            "parentCode": "000000000000000000",
            "level": 2,
            "firstCode": null,
            "firstId": null,
            "firstName": null,
            "secondCode": null,
            "secondId": null,
            "secondName": null,
            "children": [
                {
                    "institutionId": "000000000000070100",
                    "code": "20701",
                    "name": "ເມືອງ ຊຳ​ເໜືອ",
                    "remark": "Xamneua District",
                    "parentCode": "000000000000070000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000070200",
                    "code": "20702",
                    "name": "ເມືອງ ຊຽງ​ຄໍ້",
                    "remark": "Xiengkhor District",
                    "parentCode": "000000000000070000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000070300",
                    "code": "20703",
                    "name": "ເມືອງ ຮ້ຽມ",
                    "remark": "Huim District",
                    "parentCode": "000000000000070000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000070400",
                    "code": "20704",
                    "name": "ເມືອງ ວຽງ​ໄຊ",
                    "remark": "Viengxay District",
                    "parentCode": "000000000000070000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000070500",
                    "code": "20705",
                    "name": "ເມືອງ ຫົວ​ເມືອງ",
                    "remark": "Huameuang District",
                    "parentCode": "000000000000070000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000070600",
                    "code": "20706",
                    "name": "ເມືອງ ຊຳ​ໃຕ້",
                    "remark": "Xamtay District",
                    "parentCode": "000000000000070000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000070700",
                    "code": "20707",
                    "name": "ເມືອງ ສົບ​ເບົາ",
                    "remark": "Sopbao District",
                    "parentCode": "000000000000070000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000070800",
                    "code": "20708",
                    "name": "ເມືອງ ແອດ",
                    "remark": "Add District",
                    "parentCode": "000000000000070000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000070900",
                    "code": "20709",
                    "name": "ເມືອງ ກວັນ",
                    "remark": "Kuane District",
                    "parentCode": "000000000000070000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000071000",
                    "code": "20710",
                    "name": "ເມືອງ ຊ່ອນ",
                    "remark": "Sone District",
                    "parentCode": "000000000000070000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                }
            ]
        },
        {
            "institutionId": "000000000000080000",
            "code": "20800",
            "name": "ແຂວງ ໄຊ​ຍະ​ບູ​ລີ",
            "remark": "Xayabury",
            "parentCode": "000000000000000000",
            "level": 2,
            "firstCode": null,
            "firstId": null,
            "firstName": null,
            "secondCode": null,
            "secondId": null,
            "secondName": null,
            "children": [
                {
                    "institutionId": "000000000000080100",
                    "code": "20801",
                    "name": "ເມືອງ ໄຊ​ຍະ​ບູ​ລີ",
                    "remark": "Xayabury District",
                    "parentCode": "000000000000080000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000080200",
                    "code": "20802",
                    "name": "ເມືອງ ພຽງ",
                    "remark": "Phieng District",
                    "parentCode": "000000000000080000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000080300",
                    "code": "20803",
                    "name": "ເມືອງ ປາກ​ລາຍ",
                    "remark": "PakLai District",
                    "parentCode": "000000000000080000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000080400",
                    "code": "20804",
                    "name": "ເມືອງ ແກ່​ນ​ທ້າ​ວ",
                    "remark": "KianThao District",
                    "parentCode": "000000000000080000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000080500",
                    "code": "20805",
                    "name": "ເມືອງ ບໍ່​ແຕນ",
                    "remark": "BoTien District",
                    "parentCode": "000000000000080000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000080600",
                    "code": "20806",
                    "name": "ເມືອງ ຫົງ​ສາ",
                    "remark": "​HongSa District",
                    "parentCode": "000000000000080000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000080700",
                    "code": "20807",
                    "name": "ເມືອງ ຊຽງ​ຮ່ອນ",
                    "remark": "XiengHone District",
                    "parentCode": "000000000000080000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000080800",
                    "code": "20808",
                    "name": "ເມືອງ ຄອບ",
                    "remark": "Khob District",
                    "parentCode": "000000000000080000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000080900",
                    "code": "20809",
                    "name": "ເມືອງ ເງິນ",
                    "remark": "Ngern District",
                    "parentCode": "000000000000080000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000081000",
                    "code": "20810",
                    "name": "ເມືອງ ທົ່ງ​ມີ​ໄຊ",
                    "remark": "Thongmyxay District",
                    "parentCode": "000000000000080000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000081100",
                    "code": "20811",
                    "name": "ເມືອງ ໄຊ​ສະ​ຖານ",
                    "remark": "Xaysathan District",
                    "parentCode": "000000000000080000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                }
            ]
        },
        {
            "institutionId": "000000000000090000",
            "code": "20900",
            "name": "ແຂວງ ຊຽງ​ຂວາງ",
            "remark": "Xiengkhuang",
            "parentCode": "000000000000000000",
            "level": 2,
            "firstCode": null,
            "firstId": null,
            "firstName": null,
            "secondCode": null,
            "secondId": null,
            "secondName": null,
            "children": [
                {
                    "institutionId": "000000000000090100",
                    "code": "20901",
                    "name": "ເມືອງ ແປກ",
                    "remark": "Pek District",
                    "parentCode": "000000000000090000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000090200",
                    "code": "20902",
                    "name": "ເມືອງ ຄຳ",
                    "remark": "Kham District",
                    "parentCode": "000000000000090000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000090300",
                    "code": "20903",
                    "name": "ເມືອງ ​ໜອງ​ແຮດ",
                    "remark": "Nonghed District",
                    "parentCode": "000000000000090000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000090400",
                    "code": "20904",
                    "name": "ເມືອງ ຄູນ",
                    "remark": "Khoune District",
                    "parentCode": "000000000000090000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000090500",
                    "code": "20905",
                    "name": "ເມືອງ ໝອກ​ໃໝ່",
                    "remark": "Morkmay District",
                    "parentCode": "000000000000090000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000090600",
                    "code": "20906",
                    "name": "ເມືອງ ​ພູ​ກູດ",
                    "remark": "Phoukoud District",
                    "parentCode": "000000000000090000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000090700",
                    "code": "20907",
                    "name": "ເມືອງ ຜາ​ໄຊ",
                    "remark": "Phaxay District",
                    "parentCode": "000000000000090000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                }
            ]
        },
        {
            "institutionId": "000000000000100000",
            "code": "21000",
            "name": "ແຂວງ ວຽງ​ຈັນ",
            "remark": "Vientiane",
            "parentCode": "000000000000000000",
            "level": 2,
            "firstCode": null,
            "firstId": null,
            "firstName": null,
            "secondCode": null,
            "secondId": null,
            "secondName": null,
            "children": [
                {
                    "institutionId": "000000000000100100",
                    "code": "21001",
                    "name": "ເມືອງ ​ໂພນ​ໂຮງ",
                    "remark": "Phonhong District",
                    "parentCode": "000000000000100000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000100200",
                    "code": "21002",
                    "name": "ເມືອງ ທຸ​ລະ​ຄົມ",
                    "remark": "Thoulakhom District",
                    "parentCode": "000000000000100000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000100300",
                    "code": "21003",
                    "name": "ເມືອງ ແກ້ວ​ອຸ​ດົມ",
                    "remark": "Keooudom District",
                    "parentCode": "000000000000100000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000100400",
                    "code": "21004",
                    "name": "ເມືອງ ກາ​ສີ",
                    "remark": "Kasy District",
                    "parentCode": "000000000000100000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000100500",
                    "code": "21005",
                    "name": "ເມືອງ ວັງ​ວຽງ",
                    "remark": "Vangvieng District",
                    "parentCode": "000000000000100000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000100600",
                    "code": "21006",
                    "name": "ເມືອງ ເຟືອງ",
                    "remark": "Feuang District",
                    "parentCode": "000000000000100000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000100700",
                    "code": "21007",
                    "name": "ເມືອງ ​ຊະ​ນະ​ຄາມ",
                    "remark": "Xanakharm District",
                    "parentCode": "000000000000100000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000100800",
                    "code": "21008",
                    "name": "ເມືອງ ແມດ",
                    "remark": "Mad District",
                    "parentCode": "000000000000100000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000100900",
                    "code": "21009",
                    "name": "ເມືອງ ຫີນ​ເຫີບ",
                    "remark": "Hinherb District",
                    "parentCode": "000000000000100000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000101000",
                    "code": "21010",
                    "name": "ເມືອງ ໝື່ນ",
                    "remark": "Meun District",
                    "parentCode": "000000000000100000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000101100",
                    "code": "21013",
                    "name": "ເມືອງ ວຽງ​ຄຳ",
                    "remark": "Viengkham District",
                    "parentCode": "000000000000100000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                }
            ]
        },
        {
            "institutionId": "000000000000110000",
            "code": "21100",
            "name": "ແຂວງ ບໍ​ລິ​ຄຳ​ໄຊ",
            "remark": "Borikhamxay",
            "parentCode": "000000000000000000",
            "level": 2,
            "firstCode": null,
            "firstId": null,
            "firstName": null,
            "secondCode": null,
            "secondId": null,
            "secondName": null,
            "children": [
                {
                    "institutionId": "000000000000110100",
                    "code": "21101",
                    "name": "ເມືອງ ປາກ​ຊັນ",
                    "remark": "Pakxane District",
                    "parentCode": "000000000000110000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000110200",
                    "code": "21102",
                    "name": "ເມືອງ ທ່າ​ພະ​ບາດ",
                    "remark": "Thaphabath District",
                    "parentCode": "000000000000110000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000110300",
                    "code": "21103",
                    "name": "ເມືອງ ປາກ​ກະ​ດິງ",
                    "remark": "Pakkading District",
                    "parentCode": "000000000000110000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000110400",
                    "code": "21104",
                    "name": "ເມືອງ ບໍ​ລິ​ຄັນ",
                    "remark": "Bolikhanh District",
                    "parentCode": "000000000000110000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000110500",
                    "code": "21105",
                    "name": "ເມືອງ ຄຳ​ເກີດ",
                    "remark": "Khamkeuth District",
                    "parentCode": "000000000000110000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000110600",
                    "code": "21106",
                    "name": "ເມືອງ ວຽງ​ທອງ",
                    "remark": "Viengthong District",
                    "parentCode": "000000000000110000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000110700",
                    "code": "21107",
                    "name": "ເມືອງ ໄຊ​ຈຳ​ພອນ",
                    "remark": "Xaychamphone District",
                    "parentCode": "000000000000110000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                }
            ]
        },
        {
            "institutionId": "000000000000120000",
            "code": "21200",
            "name": "​​ແຂວງ ຄຳ​ມ່ວນ",
            "remark": "Khammuane",
            "parentCode": "000000000000000000",
            "level": 2,
            "firstCode": null,
            "firstId": null,
            "firstName": null,
            "secondCode": null,
            "secondId": null,
            "secondName": null,
            "children": [
                {
                    "institutionId": "000000000000120100",
                    "code": "21201",
                    "name": "ເມືອງ ທ່າ​ແຂກ",
                    "remark": "Thakhek District",
                    "parentCode": "000000000000120000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000120200",
                    "code": "21202",
                    "name": "ເມືອງ ມະ​ຫາ​ໄຊ",
                    "remark": "Mahaxay District",
                    "parentCode": "000000000000120000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000120300",
                    "code": "21203",
                    "name": "ເມືອງ ໜອງ​ບົກ",
                    "remark": "Nongbok District",
                    "parentCode": "000000000000120000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000120400",
                    "code": "21204",
                    "name": "ເມືອງ ຫິນ​ບູນ",
                    "remark": "Hinboon District",
                    "parentCode": "000000000000120000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000120500",
                    "code": "21205",
                    "name": "ເມືອງ ຍົມ​ມະ​ລາດ",
                    "remark": "Nhommalath District",
                    "parentCode": "000000000000120000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000120600",
                    "code": "21206",
                    "name": "ເມືອງ ບົວ​ລະ​ພາ",
                    "remark": "Bualapha District",
                    "parentCode": "000000000000120000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000120700",
                    "code": "21207",
                    "name": "ເມືອງ ນາ​ກາຍ",
                    "remark": "Nakai District",
                    "parentCode": "000000000000120000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000120800",
                    "code": "21208",
                    "name": "ເມືອງ ເຊບັ້ງ​ໄຟ",
                    "remark": "Xebangfay District",
                    "parentCode": "000000000000120000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000120900",
                    "code": "21209",
                    "name": "ເມືອງ ໄຊ​ບົວ​ທອງ",
                    "remark": "Xaybuathong District",
                    "parentCode": "000000000000120000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000121000",
                    "code": "21210",
                    "name": "ເມືອງ ຄູນ​ຄຳ",
                    "remark": "Khounkham District",
                    "parentCode": "000000000000120000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                }
            ]
        },
        {
            "institutionId": "000000000000130000",
            "code": "21300",
            "name": "ແຂວງ ສະ​ຫວັນ​ນະ​ເຂດ",
            "remark": "Savannakhet",
            "parentCode": "000000000000000000",
            "level": 2,
            "firstCode": null,
            "firstId": null,
            "firstName": null,
            "secondCode": null,
            "secondId": null,
            "secondName": null,
            "children": [
                {
                    "institutionId": "000000000000130100",
                    "code": "21301",
                    "name": "ນະ​ຄອນ​ໄກ​ສອນ​ພົມ​ວິ​ຫານ",
                    "remark": "KaysonePhomvihane District",
                    "parentCode": "000000000000130000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000130200",
                    "code": "21302",
                    "name": "ເມືອງ ອຸ​ທຸມ​ພອນ",
                    "remark": "Outhoomphone District",
                    "parentCode": "000000000000130000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000130300",
                    "code": "21303",
                    "name": "ເມືອງ ອາດ​ສະ​ພັງ​ທອງ",
                    "remark": "Atsaphangthong District",
                    "parentCode": "000000000000130000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000130400",
                    "code": "21304",
                    "name": "ເມືອງ ພີນ",
                    "remark": "Phine District",
                    "parentCode": "000000000000130000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000130500",
                    "code": "21305",
                    "name": "ເມືອງ ເຊ​ໂປນ",
                    "remark": "Sepone District",
                    "parentCode": "000000000000130000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000130600",
                    "code": "21306",
                    "name": "ເມືອງ ນອງ",
                    "remark": "Nong District",
                    "parentCode": "000000000000130000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000130700",
                    "code": "21307",
                    "name": "ເມືອງ ທ່າ​ປາງ​ທອງ",
                    "remark": "Thapangthong District",
                    "parentCode": "000000000000130000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000130800",
                    "code": "21308",
                    "name": "ເມືອງ ສອງ​ຄອນ",
                    "remark": "Songkhone District",
                    "parentCode": "000000000000130000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000130900",
                    "code": "21309",
                    "name": "ເມືອງ ຈຳພອນ",
                    "remark": "Champhone District",
                    "parentCode": "000000000000130000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000131000",
                    "code": "21310",
                    "name": "ເມືອງ ຊົນນະ​ບູ​ລີ",
                    "remark": "Xonnabuly District",
                    "parentCode": "000000000000130000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000131100",
                    "code": "21311",
                    "name": "ເມືອງ ໄຊ​ບູ​ລີ",
                    "remark": "Xaybuly District",
                    "parentCode": "000000000000130000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000131200",
                    "code": "21312",
                    "name": "ເມືອງ ວິ​ລະ​ບູ​ລີ",
                    "remark": "Vilabuly District",
                    "parentCode": "000000000000130000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000131300",
                    "code": "21313",
                    "name": "ເມືອງ ອາດ​ສະ​ພອນ",
                    "remark": "Atsaphone District",
                    "parentCode": "000000000000130000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000131400",
                    "code": "21314",
                    "name": "ເມືອງ ໄຊ​ພູ​ທອງ",
                    "remark": "Xayphoothong District",
                    "parentCode": "000000000000130000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000131500",
                    "code": "21315",
                    "name": "ເມືອງ ພະ​ລານ​ໄຊ",
                    "remark": "Phalanxay District",
                    "parentCode": "000000000000130000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                }
            ]
        },
        {
            "institutionId": "000000000000140000",
            "code": "21400",
            "name": "ແຂວງ ສາ​ລະ​ວັນ",
            "remark": "Saravane",
            "parentCode": "000000000000000000",
            "level": 2,
            "firstCode": null,
            "firstId": null,
            "firstName": null,
            "secondCode": null,
            "secondId": null,
            "secondName": null,
            "children": [
                {
                    "institutionId": "000000000000140100",
                    "code": "21401",
                    "name": "ເມືອງ ສາ​ລະ​ວັນ",
                    "remark": "Saravane District",
                    "parentCode": "000000000000140000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000140200",
                    "code": "21402",
                    "name": "ເມືອງ ຕະໂອ້ຍ",
                    "remark": "Ta oi District",
                    "parentCode": "000000000000140000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000140300",
                    "code": "21403",
                    "name": "ເມືອງ ຕຸ້ມ​ລານ",
                    "remark": "Toomlarn District",
                    "parentCode": "000000000000140000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000140400",
                    "code": "21404",
                    "name": "ເມືອງ ​ລະ​ຄອນ​ເພັງ",
                    "remark": "Lakhonepheng District",
                    "parentCode": "000000000000140000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000140500",
                    "code": "21405",
                    "name": "ເມືອງ ​ວາ​ປີ",
                    "remark": "Vapy District",
                    "parentCode": "000000000000140000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000140600",
                    "code": "21406",
                    "name": "ເມືອງ ຄົງ​ເຊ​ໂດນ",
                    "remark": "Khongxedone District",
                    "parentCode": "000000000000140000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000140700",
                    "code": "21407",
                    "name": "ເມືອງ ​ເລົ່າ​ງາ​ມ",
                    "remark": "Lao ngarm District",
                    "parentCode": "000000000000140000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000140800",
                    "code": "21408",
                    "name": "ເມືອງ ສະ​​ມ້ວຍ",
                    "remark": "Samuoi District",
                    "parentCode": "000000000000140000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                }
            ]
        },
        {
            "institutionId": "000000000000150000",
            "code": "21500",
            "name": "ແຂວງ ເຊກອງ",
            "remark": "Sekong",
            "parentCode": "000000000000000000",
            "level": 2,
            "firstCode": null,
            "firstId": null,
            "firstName": null,
            "secondCode": null,
            "secondId": null,
            "secondName": null,
            "children": [
                {
                    "institutionId": "000000000000150100",
                    "code": "21501",
                    "name": "ເມືອງ ລະ​ມາມ",
                    "remark": "Lamarm District",
                    "parentCode": "000000000000150000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000150200",
                    "code": "21502",
                    "name": "ເມືອງ ກະ​ລຶມ",
                    "remark": "Kaleum District",
                    "parentCode": "000000000000150000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000150300",
                    "code": "21503",
                    "name": "ເມືອງ ດາກ​ຈຶງ",
                    "remark": "Darkcheung District",
                    "parentCode": "000000000000150000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000150400",
                    "code": "21504",
                    "name": "ເມືອງ ​ທ່າ​ແຕງ",
                    "remark": "Thateng District",
                    "parentCode": "000000000000150000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                }
            ]
        },
        {
            "institutionId": "000000000000160000",
            "code": "21600",
            "name": "ແຂວງ ຈຳ​ປາ​ສັກ",
            "remark": "Champasack",
            "parentCode": "000000000000000000",
            "level": 2,
            "firstCode": null,
            "firstId": null,
            "firstName": null,
            "secondCode": null,
            "secondId": null,
            "secondName": null,
            "children": [
                {
                    "institutionId": "000000000000160100",
                    "code": "21601",
                    "name": "ນະ​ຄອນ​ປາກ​ເຊ",
                    "remark": "Pakse District",
                    "parentCode": "000000000000160000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000160200",
                    "code": "21602",
                    "name": "ເມືອງ ຊະ​ນະ​ສົມ​ບູນ",
                    "remark": "Sanasomboon District",
                    "parentCode": "000000000000160000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000160300",
                    "code": "21603",
                    "name": "ເມືອງ ບາ​ຈຽງ",
                    "remark": "Bachiangchaleunsook District",
                    "parentCode": "000000000000160000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000160400",
                    "code": "21604",
                    "name": "ເມືອງ ປາກ​ຊ່ອງ",
                    "remark": "Paksxong District",
                    "parentCode": "000000000000160000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000160500",
                    "code": "21605",
                    "name": "ເມືອງ ປະ​ທຸມ​ພອນ",
                    "remark": "Pathoomphone District",
                    "parentCode": "000000000000160000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000160600",
                    "code": "21606",
                    "name": "ເມືອງ ໂພນ​ທອງ",
                    "remark": "Phonthong District",
                    "parentCode": "000000000000160000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000160700",
                    "code": "21607",
                    "name": "ເມືອງ ຈຳ​ປາ​ສັກ",
                    "remark": "Champasack District",
                    "parentCode": "000000000000160000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000160800",
                    "code": "21608",
                    "name": "ເມືອງ ​ສຸ​ຂຸ​ມາ",
                    "remark": "Sukhuma District",
                    "parentCode": "000000000000160000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000160900",
                    "code": "21609",
                    "name": "ເມືອງ ມຸນ​ລະ​ປະ​ໂມກ",
                    "remark": "Moonlapamok District",
                    "parentCode": "000000000000160000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000161000",
                    "code": "21610",
                    "name": "ເມືອງ ໂຂງ",
                    "remark": "Khong District",
                    "parentCode": "000000000000160000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                }
            ]
        },
        {
            "institutionId": "000000000000170000",
            "code": "21700",
            "name": "ແຂວງ ອັດ​ຕະ​ປື",
            "remark": "Attapeu",
            "parentCode": "000000000000000000",
            "level": 2,
            "firstCode": null,
            "firstId": null,
            "firstName": null,
            "secondCode": null,
            "secondId": null,
            "secondName": null,
            "children": [
                {
                    "institutionId": "000000000000170100",
                    "code": "21701",
                    "name": "ເມືອງ ໄຊ​ເສດ​ຖາ",
                    "remark": "Xaysetha District",
                    "parentCode": "000000000000170000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000170200",
                    "code": "21702",
                    "name": "ເມືອງ ສາ​ມັກຄີ​ໄຊ",
                    "remark": "Samakkhixay District",
                    "parentCode": "000000000000170000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000170300",
                    "code": "21703",
                    "name": "ເມືອງ ສະ​ໜາມ​ໄຊ",
                    "remark": "Sanamxay District",
                    "parentCode": "000000000000170000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000170400",
                    "code": "21704",
                    "name": "ເມືອງ ຊານໄຊ",
                    "remark": "Sanxay District",
                    "parentCode": "000000000000170000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000170500",
                    "code": "21705",
                    "name": "ເມືອງ ພູ​ວົງ",
                    "remark": "Phouvong District",
                    "parentCode": "000000000000170000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000170600",
                    "code": "21800",
                    "name": "ແຂວງ ໄຊ​ສົມ​ບູນ",
                    "remark": "Saysomboun",
                    "parentCode": "000000000000170000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000170700",
                    "code": "21801",
                    "name": "ເມືອງ ອະ​ນຸ​ວົງ",
                    "remark": "Anouvong District",
                    "parentCode": "000000000000170000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000170800",
                    "code": "21802",
                    "name": "ເມືອງ ຮົ່ມ",
                    "remark": "Home District",
                    "parentCode": "000000000000170000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000170900",
                    "code": "21803",
                    "name": "ເມືອງ ທ່າ​ໂທມ",
                    "remark": "Thathom District",
                    "parentCode": "000000000000170000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000171000",
                    "code": "21804",
                    "name": "ເມືອງ ​ລ້ອງແຈ້ງ",
                    "remark": "Longcheng District",
                    "parentCode": "000000000000170000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                },
                {
                    "institutionId": "000000000000171100",
                    "code": "21805",
                    "name": "ເມືອງ ລ້ອງ​ຊານ",
                    "remark": "Longsane District",
                    "parentCode": "000000000000170000",
                    "level": 3,
                    "firstCode": null,
                    "firstId": null,
                    "firstName": null,
                    "secondCode": null,
                    "secondId": null,
                    "secondName": null,
                    "children": []
                }
            ]
        }
    ]
}



function flattenInstitutions(node) {
    const itemWithoutChildren = _.omit(node, ['children']);
    const flattenedChildren = _.flatMap(node.children, child => flattenInstitutions(child));
    return [itemWithoutChildren, ...flattenedChildren];
}

export const flatInstitutionsArray = flattenInstitutions(Institutions)